import { grantChatMissionXp } from '@/lib/grantChatMissionXp';

// queue_id is generated by the backend via secrets.token_hex(8) — 16 lowercase hex chars.
const QUEUE_ID_RE = /^[a-f0-9]{16}$/;

const STATUS_BASE_URL = 'http://93.118.140.186:18085/chat/status'; // سرور GPU شرکت — same host that issued the queue_id

export async function GET(request, { params }) {
  const { queueId } = await params;

  if (!QUEUE_ID_RE.test(queueId)) {
    return Response.json({ status: 'busy' }, { status: 400 });
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8_000);

  try {
    const response = await fetch(`${STATUS_BASE_URL}/${queueId}`, {
      signal: controller.signal,
    });
    if (!response.ok) throw new Error(`status ${response.status}`);
    const data = await response.json();

    if (data?.status === 'done') await grantChatMissionXp();
    return Response.json(data);
  } catch (err) {
    console.warn('Chat queue status check failed:', err.message);
    // Treat an unreachable/erroring backend the same as an expired queue entry
    // so the client shows the friendly "busy" message instead of hanging or erroring.
    return Response.json({ status: 'busy' });
  } finally {
    clearTimeout(timeout);
  }
}
