import { grantChatMissionXp } from '@/lib/grantChatMissionXp';

// queue_id is generated by the backend via secrets.token_hex(8) — 16 lowercase hex chars.
const QUEUE_ID_RE = /^[a-f0-9]{16}$/;

// A queue_id could have been issued by either backend — /chat's own primary→
// fallback logic decides which one actually served a given request, and this
// endpoint has no way to know in advance which one that was. Both backends
// return {"status":"busy"} for a queue_id they don't recognize (same as one
// that's genuinely still pending), so a "not done" response can't be told
// apart from "wrong server" — the only correct move is to try both.
const PRIMARY_URL = 'http://93.118.140.186:18085/chat/status';  // سرور GPU شرکت
const FALLBACK_URL = 'http://172.17.0.1:8000/chat/status';      // بک‌اند لوکال VPS (CPU)

async function tryFetch(baseUrl, queueId, timeoutMs) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${baseUrl}/${queueId}`, {
      signal: controller.signal,
    });
    if (!response.ok) throw new Error(`status ${response.status}`);
    return await response.json();
  } finally {
    clearTimeout(timeout);
  }
}

export async function GET(request, { params }) {
  const { queueId } = await params;

  if (!QUEUE_ID_RE.test(queueId)) {
    return Response.json({ status: 'busy' }, { status: 400 });
  }

  try {
    const data = await tryFetch(PRIMARY_URL, queueId, 8_000);
    if (data?.status === 'done') {
      await grantChatMissionXp();
      return Response.json(data);
    }
    // Not done on primary (busy, or an id primary doesn't recognize) — fall
    // through and check secondary before reporting busy to the client.
  } catch (err) {
    console.warn('Primary chat queue status check failed:', err.message);
  }

  try {
    const data = await tryFetch(FALLBACK_URL, queueId, 5_000);
    if (data?.status === 'done') await grantChatMissionXp();
    return Response.json(data);
  } catch (err) {
    console.warn('Secondary chat queue status check failed:', err.message);
    // Treat both backends unreachable/erroring the same as an expired queue
    // entry so the client shows the friendly "busy" message instead of
    // hanging or erroring.
    return Response.json({ status: 'busy' });
  }
}
